SELECT * FROM CARS;

-- PROMEDIO DE KILOMETRAJE EN EL AÑO 2018 
SELECT YEAR, CAST( avg(KM_DRIVEN) AS FLOAT) AS PROMEDIO
FROM CARS 
WHERE YEAR = 2018 ;



-- ¿hay algún auto por debajo de ese promedio?

SELECT NAME, CAST(selling_price AS FLOAT) AS SELLING_PRICE , KM_DRIVEN
FROM CARS 
WHERE KM_DRIVEN < ( SELECT  CAST( avg(KM_DRIVEN) AS FLOAT) AS PROMEDIO
					FROM CARS 
					WHERE YEAR = 2018
                        )
group by name
ORDER BY selling_price DESC, NAME  ASC;
 
-- PRECIO DE VENTA POR MODELO DE CARRO

SELECT NAME, selling_price, FUEL, COUNT(NAME) TOTAL_DE_ESTE_MODELO
FROM CARS
GROUP BY NAME
HAVING COUNT(NAME) >1
ORDER BY SELLING_PRICE DESC;

-- CANTIDAD DE AUTOS POR CADA TIPO DE COMBUSTIBLE

SELECT FUEL , COUNT(FUEL)
FROM CARS
GROUP BY FUEL 
HAVING COUNT(FUEL); 

-- TIPO DE TRANSMISION DE LOS MARUTI

SELECT NAME, TRANSMISSION, COUNT(TRANSMISSION) AS TIPO_DE_TRANSMISION
FROM CARS 
WHERE NAME LIKE 'Maruti%'
GROUP BY NAME
HAVING COUNT(TRANSMISSION) >1 ;


WITH A AS  ( 
			SELECT NAME, TRANSMISSION, COUNT(TRANSMISSION) AS TIPO_DE_TRANSMISION
			FROM CARS 
			WHERE NAME LIKE 'Maruti%'
			GROUP BY NAME
			HAVING COUNT(TRANSMISSION) >1 
)

SELECT TRANSMISSION, COUNT(TRANSMISSION) AS TOTAL
 FROM A
 group by TRANSMISSION 

